# Generated by Django 4.0a1 on 2021-09-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_amenities_created_alter_amenities_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='baths',
            new_name='bath',
        ),
    ]
